module.exports = [{
  name: 'Balabizo',
  email: 'test@gmail.com',
  shortDescription: 'This item is for testing the Business SignUp API',
  phoneNumbers: ['12345677', '22222222', '32414553'],
  password: 'blahblah1',
  confirmPassword: 'blahblah1',
  description: 'This is for testing the API',
  workingHours: 'Saturday To Thursday 8AM-5PM',
  categories: ['Language'],
  branches: ['Nasr City'],
}, {
  name: 'Balabizo',
  email: 'test@gmail.com',
  shortDescription: 'This item is for testing the Business SignUp API',
  phoneNumbers: ['12345677', '22222222', '32414553'],
  password: '',
  confirmPassword: 'blahblah',
  description: 'This is for testing the API',
  workingHours: 'Saturday To Thursday 8AM-5PM',
  categories: ['Language'],
  branches: ['Nasr City'],
}, {
  name: 'Balabizo',
  email: 'test@gmail.com',
  shortDescription: 'This item is for testing the Business SignUp API',
  phoneNumbers: ['12345677', '22222222', '32414553'],
  password: 'blabizo',
  confirmPassword: 'blahblah',
  description: 'This is for testing the API',
  workingHours: 'Saturday To Thursday 10AM-3PM',
  categories: ['Balabizo'],
  branches: ['New Cairo'],
}, {
  name: 'Balabizo',
  email: 'test@gmail.com',
  shortDescription: 'This item is for testing the Business SignUp API',
  phoneNumbers: ['12345677', '22222222', '32414553'],
  password: 'blahblah',
  confirmPassword: 'blahblah',
  description: 'This is for testing the API',
  workingHours: 'Saturday To Thursday 10AM-4PM',
  categories: [],
  branches: ['6th Of October'],
}, {
  name: 'Balabizo',
  email: 'test@gmail.com',
  shortDescription: 'This item is for testing the Business SignUp API',
  phoneNumbers: ['12345677', '22222222', '32414553'],
  password: 'blahblah',
  confirmPassword: 'blahblah',
  description: 'This is for testing the API',
  workingHours: 'Saturday To Thursday 10AM-3PM',
  categories: ['Balabizo'],
  branches: [],
}, {
  name: 'Balabizo',
  email: 'test@gmail.com',
  shortDescription: 'This item is for testing the Business SignUp API',
  phoneNumbers: ['12345677', '22222222', '32414553'],
  password: 'blahblah',
  confirmPassword: 'blahblah',
  description: 'This is for testing the API',
  workingHours: '',
  categories: ['Balabizo'],
  branches: ['New Cairo'],
}];
